config/routes.rb
Rails.application.routes.draw do
  namespace :web do
    get 'photos/index'
    get 'photos/show'
    get 'events/calendar'
  end
  get 'admin/panel'
  resources :sponsors
  resources :photos
  resources :albums
  resources :events
  resources :pages
  get 'home/home'
  resources :sections
  
  devise_scope :user do
    # Redirects signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end
  
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "home#home"
end

app/models/photo.rb
class Photo < ApplicationRecord
    belongs_to :album
    has_one_attached :image
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, :only => [:new, :edit, :create, :update, :destroy]

  # GET /photos or /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1 or /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
    @albums = Album.all
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos or /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to photo_url(@photo), notice: "Photo was successfully created." }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1 or /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to photo_url(@photo), notice: "Photo was successfully updated." }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1 or /photos/1.json
  def destroy
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url, notice: "Photo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def photo_params
      params.require(:photo).permit(:album_id, :title, :image, :description)
    end
end

app/controllers/web/photos_controller.rb
class Web::PhotosController < ApplicationController
  def index
    @albums = Album.all
  end

  def show
    @album = Album.where(id:params[:id]).first
    @photos = Photo.all
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/web/photos_helper.rb
module Web::PhotosHelper
end

app/views/web/photos/index.html.erb
<h1 class="text-center p-3">Photo Albums</h1>

<div class="row">
  <% @albums.each do |album| %>

    <div class="col-xl-4 col-lg-6 col-md-12 col-sm-12 d-flex justify-content-center">
      <div class="card text-center mb-3" style="width: 18rem; height: 13rem;">
        <div class="card-body">
          <h5 class="card-title"><%= album.title %></h5>
          <h5 class="card-title">Description: <%= album.description %></h5>
          <% if user_signed_in? %>
            <br>
            <%= link_to "Show this Album", web_photos_show_path(id: album.id), class:"btn btn-primary mt-2" %>
          <% end %>
        </div>
      </div>
      </div>
  <% end %>
  </div>
  </div>
</div>

app/views/web/photos/show.html.erb
<h1 class="text-center p-3"><%= @album.title %></h1>
  <div class="row mt-3">
    <% @album.photos.each do |photo| %>
      <div class="col-4 d-flex justify-content-center">
        <%= image_tag(photo.image, size: "285x200") %>
      </div>
    <% end %>
  </div>

<% if user_signed_in? %>
<div class="text-center mt-3">
  <%= link_to "Edit this album", edit_album_path(@album), class:"btn btn-warning mb-3" %>

  <%= button_to "Destroy this album", @album, method: :delete, class:"btn btn-danger mb-3" %>

  <%= link_to "Back to albums", albums_path, class:"btn btn-primary mb-3" %>
</div>
<% end %>