config/routes.rb
Rails.application.routes.draw do
  namespace :web do
    get 'photos/index'
    get 'photos/show'
    get 'events/calendar'
  end
  get 'admin/panel'
  resources :sponsors
  resources :photos
  resources :albums
  resources :events
  resources :pages
  get 'home/home'
  resources :sections
  
  devise_scope :user do
    # Redirects signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end
  
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "home#home"
end

app/models/album.rb
class Album < ApplicationRecord
    has_many :photos
    validates :title, :description, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
    has_one_attached :photo
    validates :title, :eventstart, :eventend, presence: true
    
    validate :has_four



    def has_four
        @events = Event.where(featured: true)
        if self.featured == true && @events.length() >= 4
            self.errors.add(:featured, "already has four featured events")
        end
    end

    def start_time
        self.eventstart ##Where 'start' is a attribute of type 'Date' accessible through MyModel's relationship
    end

    def index
        # Scope your query to the dates being shown:
        start_date = params.fetch(:start_date, Date.today).to_date
        @meetings = Meeting.where(starts_at: start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week)
      end


end

app/models/page.rb
class Page < ApplicationRecord
    belongs_to :section
	validates :title, presence: true
	has_one_attached :doc
end

app/models/photo.rb
class Photo < ApplicationRecord
    belongs_to :album
    has_one_attached :image
end

app/models/section.rb
class Section < ApplicationRecord
    has_many :pages
    validates :title, :location, presence: true

end

app/models/sponsor.rb
class Sponsor < ApplicationRecord
    has_one_attached :image
    validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :edit, :create, :update, :destroy]
  
  def panel
    puts "-------------------"
    puts "-------------------"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
    @events = Event.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, :only => [:new, :edit, :create, :update, :destroy]

  # GET /pages or /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1 or /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
    @sections = Section.all
  end

  # GET /pages/1/edit
  def edit
    @sections = Section.all
  end

  # POST /pages or /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to page_url(@page), notice: "Page was successfully created." }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1 or /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to page_url(@page), notice: "Page was successfully updated." }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1 or /pages/1.json
  def destroy
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url, notice: "Page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def page_params
      params.require(:page).permit(:title, :section_id, :position, :page_type, :destination, :visible, :content, :doc)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/views/admin/panel.html.erb
<h1 class="p-3 text-center">Admin Panel</h1>



<div class="row text-center">

    <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 d-flex justify-content-center p-3">

        <div class="card" style="width: 18rem;">
            <div class="card-body">
            <h5 class="card-title">Events</h5>
            <%= link_to"Create New Event", new_event_path, class:"btn btn-primary" %>
            <%= link_to"Show All Created Events", events_path, class:"btn btn-secondary mt-3" %>
            </div>
        </div>

    </div>


    <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 d-flex justify-content-center p-3">

        <div class="card" style="width: 18rem;">
            <div class="card-body">
            <h5 class="card-title">Sponsors</h5>
            <%= link_to"Create New Sponsors", new_sponsor_path, class:"btn btn-primary" %>
            <%= link_to"Show All Created Sponsors", sponsors_path, class:"btn btn-secondary mt-3" %>
            </div>
        </div>

    </div>

    <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 d-flex justify-content-center p-3">

        <div class="card" style="width: 18rem;">
            <div class="card-body">
            <h5 class="card-title">Photos</h5>
            <%= link_to"Create New Photo", new_photo_path, class:"btn btn-primary" %>
            <%= link_to"Show All Created Photos", photos_path, class:"btn btn-secondary mt-3" %>
            </div>
        </div>

    </div>

</div>


<div class="row text-center p-3">

    <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 d-flex justify-content-center p-3">

        <div class="card" style="width: 18rem;">
            <div class="card-body">
            <h5 class="card-title">Albums</h5>
            <%= link_to"Create New Album", new_album_path, class:"btn btn-primary" %>
            <%= link_to"Show All Created Albums", albums_path, class:"btn btn-secondary mt-3" %>
            </div>
        </div>

    </div>


    <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 d-flex justify-content-center p-3">

        <div class="card" style="width: 18rem;">
            <div class="card-body">
            <h5 class="card-title">Pages</h5>
            <%= link_to"Create New Page", new_page_path, class:"btn btn-primary" %>
            <%= link_to"Show All Created Pages", pages_path, class:"btn btn-secondary mt-3" %>
            </div>
        </div>

    </div>

    <% if current_user.role == "Developer" %>
    <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 d-flex justify-content-center p-3">

        <div class="card" style="width: 18rem;">
            <div class="card-body">
            <h5 class="card-title">Sections</h5>
            <%= link_to"Create New Section", new_section_path, class:"btn btn-primary" %>
            <%= link_to"Show All Created Sections", sections_path, class:"btn btn-secondary mt-3" %>
            </div>
        </div>

    </div>
    <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom.css" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
<script>
  tinymce.init({
    selector: '.tinymce',
    plugins: 'lists link image table code help wordcount'
  });
</script>

    
  </head>

  <body>

<nav class="navbar navbar-expand-lg bg-body-tertiary sticky-top" style="background-color: #b22234;">
  <div class="container">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">

      <li class="nav-item">
        <%= link_to"HARMONY CLUB OF WORCESTER", home_home_path, class:"btn fs-2 fw-bold text-light p-3" %>
      </li>

      <% if current_user %>
      <li class="nav-item d-flex font-weight-bold rounded text-light p-4">
        <%= link_to"Admin Panel", admin_panel_path, class:"btn btn-secondary" %>
      </li>
      <% end %>

      </ul>

      <li class="nav-item dropdown d-flex font-weight-bold rounded text-light p-3 ">
          <div class="nav-link dropdown-toggle col p-2 rounded" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="background-color: #00075e;">
            Menu
          </div>


            <ul class="dropdown-menu text-center">
              <% Section.where(location: ["Main Navigation", "Both"]).each do |s| %>
               <% if s.visible == true %>
                  
                  <li>
                      <a class="dropdown-item border-bottom" href="#">
                      <%=s.title %> &raquo;
                      </a>
                      <ul class="dropdown-menu dropdown-submenu">


                    <% s.pages.each do |p| %>
                        <li>
                          <% if p.page_type == "External URL" %>
                            <%= link_to p.title, p.destination, class: "btn w-100 border-bottom", target: :_blank %>
                          <% end %>

                          <% if p.page_type == "Basic Page" %>
                            <a> <%= link_to p.title, p, class:"btn w-100 border-bottom" %></a>
                          <% end %>

                          <% if p.page_type == "PDF" %>
                            <a> <%= link_to p.title, p, class:"btn w-100 border-bottom" %></a>
                          <% end %>

                          <% if p.page_type == "Internal URL" %>
                            <a> <%= link_to p.title, p.destination, class:"btn w-100 border-bottom" %></a>
                          <% end %>
                        </li>
                      <% end %>
                  </ul>
                  </li>
                <% end %>
              <% end %>
              
              

            <li>
            <a class=dropdown-item" href="#"> <%= link_to "Calendar", web_events_calendar_path, class: "btn w-100 border-bottom" %> </a>
            </li>

            <li>
            <a class=dropdown-item" href="#"> <%= link_to "Sponsors", sponsors_path, class: "btn w-100 border-bottom" %> </a>
            </li>

            <li>
            <a class=dropdown-item" href="#"> <%= link_to "Gallery", web_photos_index_path, class: "btn w-100 border-bottom" %> </a>
            </li>
            
  
              <% if current_user %>
            <%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link mt-1" %>
              <% else %>
                <%= link_to "Sign In", users_path, class: "nav-link mt-1" %>
            <% end %></a>
            </li>
          </ul>
      </li>


      

    </div>

    
  </div>

  
</nav>

  <div class="container bg bg-light mb-0" id="pagecon">
    <%= yield %>
  </div>

  <div class="footer text-light mt-0" style="background-color: #b22234;">

    <div class="container text-center">
        <%= link_to"HARMONY CLUB OF WORCESTER | 2023", home_home_path, class:"btn fw-bold text-light mb-0" %>
    </div>


<div class="row">

                    <% Section.where(location: ["Footer", "Both"]).each do |s| %>
                    <% if s.visible == true %>
                    <div class="col-3">

                        <h5><%= s.title %></h5>
                          <% s.pages.each do |p| %>

                                <% if p.page_type == "External URL" %>
                                  <%= link_to p.title, p.destination, class: "btn w-100 text-light", target: :_blank %>
                                <% end %>

                                <% if p.page_type == "Basic Page" %>
                                  <a> <%= link_to p.title, p, class:"btn w-100 text-light" %></a>
                                <% end %>

                                <% if p.page_type == "PDF" %>
                                  <a> <%= link_to p.title, p, class:"btn w-100 text-light" %></a>
                                <% end %>

                                <% if p.page_type == "Internal URL" %>
                                  <a> <%= link_to p.title, p.destination, class:"btn w-100 text-light" %></a>
                                <% end %>

                            <% end %>
                    </div>
                      <% end %>
                    <% end %>        
        
                  </li>

  </div>

  <div class="col-5">

  </div>


</div>
  
  </div>

  </body>
</html>

app/views/pages/_form.html.erb
<div class="text-center">

<%= form_with(model: page) do |form| %>
  <% if page.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div data-controller="page">

    <div>
      <%= form.label :page_type, style: "display: block" %>
      <%= form.select :page_type,
                      ['Basic Page', 'Internal URL', 'External URL', 'PDF'],
                      {},
                      data: {
                        action: "change->page#toggle",
                        "page_target": "input"
                      }
      %>

    </div>


    <div>
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title %>
    </div>

    <div>
      <%= form.label :section_id, style: "display: block" %>
      <%= form.collection_select :section_id, @sections, :id, :title, prompt: "Select Section" %>
    </div>

    <div>
      <%= form.label :position, style: "display: block" %>
      <%= form.number_field :position %>
    </div>

    <div>
      <%= form.label :visible, style: "display: block" %>
      <%= form.check_box :visible %>
    </div>

    <div data-page-target="url">
      <%= form.label :destination, style: "display: block" %>
      <%= form.text_field :destination %>
    </div>

    <div data-page-target="pdf">
      <%= form.label :doc, style: "display: block" %>
      <%= form.file_field :doc, class:" ms-5 mb-3" %>
    </div>
    
    <div data-page-target="basicPage">

      <%= form.text_area :content, :class => "tinymce" %>

    </div>

  </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>

  

</div>

app/views/pages/_page.html.erb
<div id="<%= dom_id page %>">
  <p>
    <strong>Title:</strong>
    <%= page.title %>
  </p>

  <p>
    <strong>Section:</strong>
    <%= page.section_id %>
  </p>

  <p>
    <strong>Position:</strong>
    <%= page.position %>
  </p>

  <p>
    <strong>Page type:</strong>
    <%= page.page_type %>
  </p>

  <p>
    <strong>Destination:</strong>
    <%= page.destination %>
  </p>

  <p>
    <strong>Visible:</strong>
    <%= page.visible %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= page.content %>
  </p>

</div>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Back to pages", pages_path, class: "btn btn-primary" %>
</div>

app/views/pages/index.html.erb
<h1 class="text-center p-3">Pages</h1>

<div class="row">
  <% @pages.each do |page| %>

    <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 d-flex justify-content-center">
      <div class="card text-center mb-3" style="width: 18rem; height: 24rem;">
        <div class="card-body">
          <h5 class="card-title">Title: <%= page.title %></h5>
          <h5 class="card-title">Section: <%= page.section.title %></h5>
          <h5 class="card-title">Position: <%= page.position %></h5>
          <h5 class="card-title">Page Type: <%= page.page_type %></h5>
          <h5 class="card-title">Destination: <%= page.destination %></h5>
          <h5 class="card-title">Visible: <%= page.visible %></h5>
          <% if user_signed_in? %>
            <br>
            <%= link_to "Show this Page", page, class:"btn btn-primary " %>
          <% end %>
        </div>
      </div>
      </div>
  <% end %>
  </div>
  </div>
</div>

app/views/pages/new.html.erb
<div class="text-center">

<h1>New page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Back to pages", pages_path, class:"btn border border-secondary mb-3" %>
</div>

</div>

app/views/pages/show.html.erb
<div class="text-center">
<h1 class="p-3"><%= @page.title %></h1>
</div>

<p class="mb-0 p-1"> <%= @page.content.html_safe %> </p>

<% if @page.doc.attached? %>
    <embed src="<%= polymorphic_url(@page.doc) %>" type="application/pdf">
<% end %>

<hr>
<div class="text-center">
    <%= link_to "Edit this page", edit_page_path(@page), class: "btn btn-warning mt-2" %>

    <%= button_to "Destroy this page", @page, method: :delete, class: "btn btn-danger mt-2" %>

    <%= link_to "Back to pages", pages_path, class: "btn btn-primary mt-2 mb-2" %>
</div>