config/routes.rb
Rails.application.routes.draw do
  namespace :web do
    get 'photos/index'
    get 'photos/show'
    get 'events/calendar'
  end
  get 'admin/panel'
  resources :sponsors
  resources :photos
  resources :albums
  resources :events
  resources :pages
  get 'home/home'
  resources :sections
  
  devise_scope :user do
    # Redirects signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end
  
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "home#home"
end

app/models/event.rb
class Event < ApplicationRecord
    has_one_attached :photo
    validates :title, :eventstart, :eventend, presence: true
    
    validate :has_four



    def has_four
        @events = Event.where(featured: true)
        if self.featured == true && @events.length() >= 4
            self.errors.add(:featured, "already has four featured events")
        end
    end

    def start_time
        self.eventstart ##Where 'start' is a attribute of type 'Date' accessible through MyModel's relationship
    end

    def index
        # Scope your query to the dates being shown:
        start_date = params.fetch(:start_date, Date.today).to_date
        @meetings = Meeting.where(starts_at: start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week)
      end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, :only => [:new, :edit, :create, :update, :destroy]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :allday, :eventstart, :eventend, :occurence, :featured, :details)
    end
end

app/controllers/web/events_controller.rb
class Web::EventsController < ApplicationController
  def calendar
    @events = Event.all
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/web/events_helper.rb
module Web::EventsHelper
end

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">
  <p>
    <strong>Title:</strong>
    <%= event.title %>
  </p>

  <p>
    <strong>Allday:</strong>
    <%= event.allday %>
  </p>

  <p>
    <strong>Eventstart:</strong>
    <%= event.eventstart %>
  </p>

  <p>
    <strong>Eventend:</strong>
    <%= event.eventend %>
  </p>

  <p>
    <strong>Occurence:</strong>
    <%= event.occurence %>
  </p>

  <p>
    <strong>Details:</strong>
    <%= event.details %>
  </p>

</div>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :allday, style: "display: block" %>
    <%= form.check_box :allday %>
  </div>

  <div>
    <%= form.label :eventstart, style: "display: block" %>
    <%= form.datetime_field :eventstart %>
  </div>

  <div>
    <%= form.label :eventend, style: "display: block" %>
    <%= form.datetime_field :eventend %>
  </div>

  <div>
    <%= form.label :occurence, style: "display: block" %>
    <%= form.number_field :occurence %>
  </div>

  <div>
    <%= form.label :featured, style: "display: block" %>
    <%= form.check_box :featured %>
  </div>

  <div>
    <%= form.label :details, style: "display: block" %>
    <%= form.text_area :details %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Show this event", @event %> |
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/index.html.erb
<h1 class="text-center p-3">Events</h1>

<div class="row">
  <% @events.each do |event| %>

    <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 d-flex justify-content-center">
      <div class="card text-center mb-3" style="width: 18rem; height: 20rem;">
        <div class="card-body">
          <h5 class="card-title">Title: <%= event.title %></h5>
          <h5 class="card-title">Start: <%= event.eventstart.strftime('%b %d, %Y') %></h5>
          <h5 class="card-title">End: <%= event.eventend.strftime('%b %d, %Y') %></h5>
          <h5 class="card-title">Details: <%= event.details %></h5>
          <% if user_signed_in? %>
            <br>
            <%= link_to "Show this Event", event, class:"btn btn-primary" %>
          <% end %>
        </div>
      </div>
      </div>
  <% end %>
  </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="text-center">

<h1>New event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Back to events", events_path, class:"btn border border-secondary mb-3" %>
</div>

</div>

app/views/events/show.html.erb
<div class="text-center">

<%= render @event %>

<%= link_to "Back to Calendar", web_events_calendar_path, class:"btn btn-primary mb-3" %>


<% if user_signed_in? %>
<div>
  <%= link_to "Edit this event", edit_event_path(@event), class:"btn btn-warning mb-3" %>

  <%= button_to "Destroy this event", @event, method: :delete, class:"btn btn-danger mb-3" %>
</div>
</div>
<% end %>