config/routes.rb
Rails.application.routes.draw do
  namespace :web do
    get 'photos/index'
    get 'photos/show'
    get 'events/calendar'
  end
  get 'admin/panel'
  resources :sponsors
  resources :photos
  resources :albums
  resources :events
  resources :pages
  get 'home/home'
  resources :sections
  
  devise_scope :user do
    # Redirects signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end
  
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "home#home"
end

app/models/sponsor.rb
class Sponsor < ApplicationRecord
    has_one_attached :image
    validates :title, presence: true
end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController
  before_action :set_sponsor, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, :only => [:new, :edit, :create, :update, :destroy]

  # GET /sponsors or /sponsors.json
  def index
    @sponsors = Sponsor.all
  end

  # GET /sponsors/1 or /sponsors/1.json
  def show
  end

  # GET /sponsors/new
  def new
    @sponsor = Sponsor.new
  end

  # GET /sponsors/1/edit
  def edit
  end

  # POST /sponsors or /sponsors.json
  def create
    @sponsor = Sponsor.new(sponsor_params)

    respond_to do |format|
      if @sponsor.save
        format.html { redirect_to sponsor_url(@sponsor), notice: "Sponsor was successfully created." }
        format.json { render :show, status: :created, location: @sponsor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sponsors/1 or /sponsors/1.json
  def update
    respond_to do |format|
      if @sponsor.update(sponsor_params)
        format.html { redirect_to sponsor_url(@sponsor), notice: "Sponsor was successfully updated." }
        format.json { render :show, status: :ok, location: @sponsor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sponsors/1 or /sponsors/1.json
  def destroy
    @sponsor.destroy

    respond_to do |format|
      format.html { redirect_to sponsors_url, notice: "Sponsor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sponsor
      @sponsor = Sponsor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sponsor_params
      params.require(:sponsor).permit(:title, :website, :image)
    end
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/views/sponsors/_form.html.erb
<%= form_with(model: sponsor) do |form| %>
  <% if sponsor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(sponsor.errors.count, "error") %> prohibited this sponsor from being saved:</h2>

      <ul>
        <% sponsor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :website, style: "display: block" %>
    <%= form.text_field :website %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image, class:" ms-5 mb-3" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sponsors/_sponsor.html.erb
<div id="<%= dom_id sponsor %>">
  <p>
    <strong>Title:</strong>
    <%= sponsor.title %>
  </p>

  <p>
    <strong>Website:</strong>
    <%= sponsor.website %>
  </p>

</div>

app/views/sponsors/edit.html.erb
<h1>Editing sponsor</h1>

<%= render "form", sponsor: @sponsor %>

<br>

<div>
  <%= link_to "Show this sponsor", @sponsor %> |
  <%= link_to "Back to sponsors", sponsors_path %>
</div>

app/views/sponsors/index.html.erb
<h1 class="text-center p-3">Sponsors</h1>

<div class="row">
  <% @sponsors.each do |sponsor| %>

    <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 d-flex justify-content-center">
      <div class="card text-center mb-3" style="width: 20rem; height: 22rem;">
        <%= image_tag(sponsor.image, size: "317x200") %>
        <div class="card-body">
          <h5 class="card-title"><%= sponsor.title %></h5>
          <%= link_to"Visit Site", sponsor.website, class: "btn btn-primary", target: :_blank %>
          <% if user_signed_in? %>
            <br>
            <%= link_to "Show this sponsor", sponsor, class:"btn border-bottom" %>
          <% end %>
        </div>
      </div>
      </div>
  <% end %>
  </div>
  </div>
</div>

app/views/sponsors/new.html.erb
<div class="text-center">

<h1>New sponsor</h1>

<%= render "form", sponsor: @sponsor %>

<br>

<div>
  <%= link_to "Back to sponsors", sponsors_path, class:"btn border border-secondary mb-3"  %>
</div>
</div>

app/views/sponsors/show.html.erb
<div class="text-center">

<h1 class="p-3"><%= @sponsor.title %></h1>
<h5> Location : <%= @sponsor.website %></h5>

<div>
    <%= link_to "Edit this sponsor", edit_sponsor_path(@sponsor), class: "btn btn-warning mt-2" %>

    <%= button_to "Destroy this sponsor", @sponsor, method: :delete, class: "btn btn-danger mt-2" %>

    <%= link_to "Back to sponsors", sponsors_path, class: "btn btn-primary mt-2 mb-2" %>
</div>
</div>